# Generated by Django 4.1 on 2023-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_teacher_languages_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='religion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
