# Generated by Django 4.1 on 2023-05-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=200)),
                ('religion', models.CharField(choices=[('OBC', 'OBC'), ('OEC', 'OEC'), ('General', 'General')], default='', max_length=200)),
                ('photo', models.FileField(upload_to='student_photo')),
                ('Aadhar', models.FileField(upload_to='student_Aadhar')),
                ('Signature', models.FileField(upload_to='student_Signature')),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('guardianname', models.CharField(max_length=200)),
                ('guardian_contact_number', models.CharField(max_length=200)),
                ('relationship_of_guardian', models.CharField(max_length=200)),
                ('signacher_of_guardian', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('school_location', models.CharField(max_length=200)),
                ('sslc_total_persantage', models.IntegerField()),
                ('sslc_pass_out_year', models.DateField()),
                ('sslc_certificate_upload', models.FileField(upload_to='sslc_certificate')),
                ('higher_secondary_chool_name', models.CharField(max_length=200)),
                ('higher_secondary_school_location', models.CharField(max_length=200)),
                ('higher_secondary_total_mark', models.IntegerField()),
                ('higher_secondary_certificate_upload', models.FileField(upload_to='higher_secondary_certificate')),
            ],
        ),
    ]
