# Generated by Django 4.1 on 2023-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
