# Generated by Django 4.1 on 2023-05-06 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentapplication_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='higher_secondary_pass_out_year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
