# Generated by Django 4.1 on 2023-05-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentapplication_higher_secondary_pass_out_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='contact_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='guardian_contact_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='signacher_of_guardian',
            field=models.FileField(upload_to=''),
        ),
    ]
