# Generated by Django 4.1 on 2023-05-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentapplication_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='Aadhar',
            field=models.FileField(upload_to='Aadhar'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='higher_secondary_certificate_upload',
            field=models.FileField(upload_to='HS_certificate'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='higher_secondary_pass_out_year',
            field=models.DateField(verbose_name='pass out year'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='photo',
            field=models.FileField(upload_to='Photo'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='signacher_of_guardian',
            field=models.FileField(upload_to='signacher'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='sslc_pass_out_year',
            field=models.DateField(verbose_name='Pass Of year'),
        ),
    ]
