# Generated by Django 4.1 on 2023-05-22 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentapplication_aadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='join_year',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
