# Generated by Django 4.1 on 2023-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentapplication_join_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='join_year',
            field=models.DateField(auto_now_add=True),
        ),
    ]
