# Generated by Django 4.1 on 2023-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentapplication_join_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='join_year',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
