# Generated by Django 4.1 on 2023-05-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_studentapplication_join_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='join_year',
        ),
    ]
